// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW5hFK6VWvANyzehkkM-NYPEunOWMbQwI',
    appId: '1:839125335573:android:8bbbc25510c35ea4a8581c',
    messagingSenderId: '839125335573',
    projectId: 'audition-887d5',
    storageBucket: 'audition-887d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWQGZF8uXOTYNSaBvB07-2N3HnANUt81k',
    appId: '1:839125335573:ios:c6550d4d0a8522efa8581c',
    messagingSenderId: '839125335573',
    projectId: 'audition-887d5',
    storageBucket: 'audition-887d5.firebasestorage.app',
    androidClientId: '839125335573-3lpt80e73l557hkgl3q1hgbt0o8m7gsa.apps.googleusercontent.com',
    iosClientId: '839125335573-5226j6eh7qcqa5n9dtstmpmcddo1kt4a.apps.googleusercontent.com',
    iosBundleId: 'com.bg.biggee',
  );
}
